### ISSUE TITLE
[Feature Request] Add an option to hide default commands

### ISSUE THREAD

**Issue by lynncyrin** [go-jira/go-jira#261]
### What

I would like the option to hide certain default commands that I don't intend on using.

### Why

In an ideal world, I would setup my custom commands and only use those. The really powerful custom command syntax enables this super effectively 💖. I have all my custom commands now, but the help still has a bunch of commands I don't need. Ideally I would be able to do `jira --help` and the only commands that get output are the ones I already know are relevant to what I need to do.

### How

I'm imagining a config option like this

```yaml
# config.yml
hide-commands:
  - worklog add
  - unexport-template
  - transmeta
```

That applies the `hidden` property to those commands.

### Who

I would prefer to create the PR for this myself, unless an existing contributor explicitly wants to implement themselves. I'll start on that if I get >=1 👍 react from a contributor (and ping that person for the code review).

**Comment by lynncyrin** [comment]
Talked to @coryb about this just now, and I might want to do something slightly different here? I'll investigate 🔍

**Comment by lynncyrin** [comment]
Definitely wanna do something different here, closing!

**Comment by TheKevJames** [comment]
@lynncyrin I'm hoping for basically the same thing as your original request -- what was the "something different" you ended up doing to resolve this? /cc @coryb in case you recall!

**Comment by lynncyrin** [comment]
@TheKevJames read from here and down! https://gophers.slack.com/archives/CK2BQRMP1/p1559269896000200

Here's the invite if you aren't in the gophers slack already => https://invite.slack.golangbridge.org/

**Comment by TheKevJames** [comment]
@lynncyrin thanks for the lint and the invite! Sounds like you ended up implementing this as a forked internal command, then? Any chance there's a public copy of that work somewhere (I couldn't find a fork)?
