### ISSUE TITLE
`jira login` should support reading from stdlin

### ISSUE THREAD

**Issue by kojustin** [go-jira/go-jira#262]
There are use cases where it would be useful for `jira login` to read the password from stdin. For example, if there is a system that generates one-time passwords for use with jira using either the `keyring` or `pass` password sources is awkward. Or if I had some other command line tool that was able to fetch passwords for me, it would be nice if I could just do

```bash
./password-generator | jira login --username=ME
```

**Comment by mafrosis** [comment]
Second this one. I use 1password's `op` command, and cannot pipe my password into `jira login`

**Comment by coryb** [comment]
The code for the password collection is here:
https://github.com/go-jira/go-jira/blob/master/jiracli/password.go#L39

We could either implement a bypass to skip the survey.Ask prompt and just read from stdin when no tty detected, or you could implement some other password-source configuration, maybe something like:
```
password-source: custom
password-custom-command: ./password-generator
```

Either way, most of us have very limited time, but PRs are very welcome.
